GTNewHorizons/TecTech

- src/main/java/com/github/technus/tectech/mechanics/structure/StructureUtility.java
GTNewHorizons/GT-New-Horizons-Modpack#7566
> Fix air check in structure check

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
- src/main/java/com/github/technus/tectech/thing/CustomItemList.java
- src/main/java/com/github/technus/tectech/thing/item/PowerPassUpgradeCover.java
No idea if either works correctly, recipe of PPC might need changing, it seems no one ever set one.
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7538
> Fix ender fluid link and power pass cover recipes

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
now UMV energy hatch is craftable
> Fix UEV energy hatch research conflict

- build.gradle.kts
- src/main/java/com/github/technus/tectech/loader/MainLoader.java
related to https://github.com/GTNewHorizons/GT5-Unofficial/pull/606
> Moved hazmat protection to gt5u, updated gradle

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8250
Also corrected comments.
> Fixes silicone

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
see #9131, change from 3760 to 4608 for better automation
> Adjust ultimate battery soldering alloy amount

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
> Change computation & time requirements on infinite pump.

- src/main/java/com/github/technus/tectech/recipe/TT_recipeAdder.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9606
> Fix persistent hash not set on some assline recipes

- build.gradle
- src/main/java/com/github/technus/tectech/recipe/TT_recipeAdder.java
Since we decided that an Assemblyline with 16 inputs is allowed, we have to change the input check to not kick out any recipes with 16 inputs.
> Long Assline

- build.gradle
- dependencies.gradle
- repositories.gradle
mainly trying to get GitHub action to wake up ...
> maven and publication

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
i hope it will be the last time to fix the oredict thing ,,,
> fix oredict for infinity drill

- src/main/java/com/github/technus/tectech/loader/TecTechConfig.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_TM_teslaCoil.java
close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10113
> add config for tesal tower visual effect

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
> Add infinity coils.

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_DebugPowerGenerator.java
- src/main/resources/assets/tectech/lang/en_US.lang
close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10057
> laser mode for debug gen

- src/main/java/com/github/technus/tectech/thing/item/ElementalDefinitionScanStorage_EM.java
@Kiwi233  and I wasted a lot of time trying to figure out if it was working and why it wasn't working
> Fix ScanStorage not work

- src/main/java/com/github/technus/tectech/thing/cover/GT_Cover_TM_PowerPassUpgrade.java
Make Power Pass cover actually useable.
> Fix Power Pass cover

- src/main/java/com/github/technus/tectech/mechanics/enderStorage/EnderLinkCoverMessage.java
- src/main/java/com/github/technus/tectech/thing/cover/GT_Cover_TM_EnderFluidLink.java
Fix: [GT-New-Horizons-Modpack/issues/9707](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9707)
> Fix ender link cover private mode

- dependencies.gradle
- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
- src/main/java/com/github/technus/tectech/nei/TT_NEI_ResearchHandler.java
- src/main/java/com/github/technus/tectech/nei/TT_NEI_ScannerHandler.java
Eternal coil:
Eternal singularity 4 -> 1
Spacetime screws 16 -> 8
Stargate:
Nerf Nt usage
Add more long rods
Add UMV parts recipe
Refactor code
> Endgame adjustments

- src/main/java/com/github/technus/tectech/loader/recipe/BaseRecipeLoader.java
Fixes: [GT-New-Horizons-Modpack/issues/10729](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10729)
> Add a recipe for the Front rotation tool

- src/main/java/com/github/technus/tectech/mechanics/enderStorage/EnderFluidContainer.java
Fixes [GT-New-Horizons-Modpack/issues/10800](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10800)
> Fix Ender fluid link cover saving data so it doesn't shift fluid when updating

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
The card is already fully working so why not add a recipe for it.
> Added recipe for parametrizer memory card

- dependencies.gradle
- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
> changing UIV/UMV energy hatch and dynamo to use their own SC, also nerfed stargate lol

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
Backported rotation logic from enhanced mulitblock base to allow all TT based machines to be rotated more freely.
> Multiblock rotation improvement

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
Replace https://github.com/GTNewHorizons/GoodGenerator/pull/70
> reduce visibility

- build.gradle
- dependencies.gradle
- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
update Infinity Oil rig recipe use Oilrig iv
> update Infinity Oil rig recipe use Oilrig iv

- src/main/java/com/github/technus/tectech/loader/MainLoader.java
- src/main/java/com/github/technus/tectech/util/CommonValues.java
> Don't overwrite GT_Values

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_research.java
Replaced progress with computation info for the Research Station in WAILA
> Improved Resarch Station WAILA Information

- src/main/java/com/github/technus/tectech/loader/MainLoader.java
Keeps the TF adjustments because they are specific values and make more sense than setting everything to 5.
> Don't change all non-whitelisted blocks' resistance to 5.

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_infuser.java
Fixes possible dupe bugs with infuser
> Added start and end processing call to infuser to sync ME bus

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Address issue stated in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7649
> Allow any of 360k coolant for UHV Energy Hatch / Dynamo Hatch

- src/main/java/com/github/technus/tectech/nei/TT_NEI_ResearchHandler.java
- src/main/java/com/github/technus/tectech/nei/TT_NEI_ScannerHandler.java
needs https://github.com/GTNewHorizons/GT5-Unofficial/pull/1424
> no-more-duplicate-key

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
part of https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/424
> replace coils in high tier circuits with inductor smd

- src/main/java/com/github/technus/tectech/mechanics/enderStorage/EnderFluidContainer.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11298
> Properly fix ender fluid container not saving stuff

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11720
> remove inconsistent lubricant recipe in uhv

- src/main/java/com/github/technus/tectech/mechanics/enderStorage/EnderWorldSavedData.java
Requested by glee8e in https://github.com/GTNewHorizons/TecTech/pull/112 after merge.
> Check if unloaded world is dim 0 in fluid cover world saved data

- src/main/java/com/github/technus/tectech/recipe/TT_recipeAdder.java
See https://github.com/GTNewHorizons/GT5-Unofficial/pull/1529
> Make AL recipes always visible

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Oversight in https://github.com/GTNewHorizons/TecTech/pull/110
> Remove inconsistent lubricant recipe in uhv part 2

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
This allows the manipulation of input parameters by click on them. A pop up will then appear which allows you to enter the desired value.
> Advanced MUI integration

- dependencies.gradle
- repositories.gradle
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_Param.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_ParamText.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
In favor of https://github.com/GTNewHorizons/TecTech/pull/125
Also automatically set focus on popup window when opened
> Add deprecation tooltip to Parametrizers

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/Parameters.java
The old one needs both provided. This one will only update the desired.
> Added overloaded trySetParameters which only sets one parameter

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
fixes there being 4 instead of 1 uxv machine hull in the recipe for uxv energy hatches/dynamos
> Fix uxv hull amount in uxv energy/dynamo hatches

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
- src/main/java/com/github/technus/tectech/loader/thing/MachineLoader.java
- src/main/java/com/github/technus/tectech/thing/CustomItemList.java
EV Energy and Dynamo Hatches
4 amp
16 amp
64 amp
> Ev hatches

- dependencies.gradle
- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
More optical circuit recipes, more stuff to come
moved optical processor from coremod to allow optical fiber cable
> Optical circuit recipes

- build.gradle
- dependencies.gradle
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12371
> Fix me output hatch

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Nano purge part 3 or so
Change optical memory circuit assembler recipe to uhv to avoid softlock
> Nano Purge + optical fixes

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Replaces remaining nano circuits with any UIV ones and adds 2 more advanced optical memory recipes
> purge remaining nanos, more memory recipes

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
- src/main/java/com/github/technus/tectech/recipe/EyeOfHarmonyRecipeStorage.java
- src/main/java/com/github/technus/tectech/thing/CustomItemList.java
- src/main/java/com/github/technus/tectech/thing/block/RenderEyeOfHarmony.java
- src/main/java/com/github/technus/tectech/thing/casing/GT_Block_CasingsBA0.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
- src/main/resources/assets/tectech/lang/en_US.lang
Fixes up the recipe issues and should allow for people to actually craft the multi now.
> EOH Fixes/Recipes

- dependencies.gradle
- repositories.gradle
- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
> Fix EOH Recipe

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Fix all the space and time recipes in TT. They were all gone. Might also help with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12603
> Fixing space and time

- src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Buffs the amount of fun people have crafting stargate and adds recipes for UXV parts.
Still need to edit the recipes in scripts to add UXV parts and spice them up a little more generally.
> UXV Parts + Nerf Stargate

- dependencies.gradle
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
Increases precision of LED configuration window to 8 digits
> Increased parameter LED configuration precision

- src/main/java/com/github/technus/tectech/recipe/EyeOfHarmonyRecipe.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Fixes some misc issues with EOH like wrong scanner info, speed calculations and outputs
> Fix misc EOH issues

- src/main/java/com/github/technus/tectech/mechanics/data/ChunkDataHandler.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12802
> fix ChunkDataHandler causing CME at chunk unload

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
first one in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12889
> patch weird NPE

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
With MUI implementation it accepted stacks with more than 1 items.
> Fix research station inventory

- src/main/java/com/github/technus/tectech/proxy/ClientProxy.java
- src/main/java/com/github/technus/tectech/recipe/EyeOfHarmonyRecipe.java
- src/main/java/com/github/technus/tectech/thing/block/EyeOfHarmonyBlock.java
- src/main/java/com/github/technus/tectech/thing/block/RenderEyeOfHarmony.java
- src/main/java/com/github/technus/tectech/thing/block/TileEyeOfHarmony.java
- src/main/java/com/github/technus/tectech/thing/casing/TT_Container_Casings.java
- src/main/java/com/github/technus/tectech/thing/item/RenderEyeOfHarmonyItem.java
Buffs the plasma output of the EOH by 8x because it was not enough to replace compact fusion spam for dtpf plasmas
Also added the 5 missing plasmas for exotic catalyst to the DD recipe
> Fix some EOH rendering issues and buff EOH plasma output by 8x. DD now also gives all plasmas for exotic catalyst

- src/main/java/com/github/technus/tectech/thing/item/ParametrizerMemoryCard.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/Parameters.java
- src/main/resources/assets/tectech/lang/en_US.lang
- Allow copy-pasting parameters from/to multiblock controller
- Show current mode of the card to display name
> Parametrizer Memory Card improvements

- src/main/java/com/github/technus/tectech/loader/recipe/Assembler.java
Directly change chrome to rhodium palladium if BW exists.
> Integrate BW material replacements

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Fixes the overflow calculations of the EOH always returning 0
> Fix EOH overflow calculations

- build.gradle
- dependencies.gradle
- src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
> Fix infinity plate

- .gitignore
- repositories.gradle
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_DynamoTunnel.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_Pipe_Energy.java
Allows MuTEs to connect to a laser network if they have lasers enabled
> Enable MuTEs to have lasers

- src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
Adjusts uxv part recipe times and voltages to follow the trend of the previous tiers (50 seconds, tier-1 voltage)
> Adjust uxv part recipes

- dependencies.gradle
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_PipeBlock_Data.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_PipeBlock_EM.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_PipeBlock_Energy.java
- src/main/resources/assets/tectech/lang/en_US.lang
Increases the explosion resistance of the casing variants of laser/data/matter pipe, to make them blast proof.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13040
> Added higher explosion resistance to pipe casings

- src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
> butcher controller recipe time

- src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
Fixes part of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13615
> Fix TPM recipe voltage

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Some small EOH tooltip improvements & typo fixes
> EOH tooltip touch-up

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Fixes the casing amount in the tooltip
> Fix Infinite Spacetime Energy Boundary casing amount in EOH tooltip

- src/main/java/com/github/technus/tectech/mechanics/spark/RendererMessage.java
Follow-up to https://github.com/GTNewHorizons/TecTech/pull/234
> Validate ObjectInputStream

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
> Fix TT extended Multis using wrong exotic energy input hatches list

- src/main/java/com/github/technus/tectech/loader/thing/MachineLoader.java
Should fix the usage of TT with GTNH Intergalactic
> Fix missing item crash

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_TM_teslaCoil.java
this should remove the log spam on zeta
> fix ofBlocksTiered notSet misuse

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/Parameters.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14737
> Fix missing method

- dependencies.gradle
- src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
For https://github.com/GTNewHorizons/KubaTech/pull/101
> Fix recipes after DEFC movement

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Fixes the following nuclear info panel & EOH related crash 
[crash.txt](https://github.com/GTNewHorizons/TecTech/files/13552516/message.5.txt)
> Fix EOH + nuclear info panel crash

- src/main/java/com/github/technus/tectech/recipe/EyeOfHarmonyRecipeStorage.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15012
> Fix EOH not accepting input fluids

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15747
This PR makes the EoH scanner info display the average star matter and stellar plasma output instead of showing the actual output of the current recipe to prevent cheese.
> Fix predetermined eoh outputs showing on scanner info

- src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Fixes the recent scanner data related NPEs
> Fix EoH NPE

- src/main/java/com/github/technus/tectech/loader/recipe/BaseRecipeLoader.java
- src/main/java/com/github/technus/tectech/loader/thing/MachineLoader.java
- src/main/java/com/github/technus/tectech/loader/thing/ThingsLoader.java
The multi isnt done and its blocks and recipes shouldnt go into stable in their current state
> Don't load godforge 
