GTNewHorizons/TecTech

src/main/java/com/github/technus/tectech/nei/TT_NEI_ResearchHandler.java, src/main/java/com/github/technus/tectech/nei/TT_NEI_ScannerHandler.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_DataConnector.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_DynamoTunnel.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_EnergyMulti.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_EnergyTunnel.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_OverflowElemental.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_decay.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_research.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_scanner.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_DataReader.java
Add number formatting to portable scanner output and tooltips.
See:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8346
I loaded up the game and looked at a bunch of tooltips and scanner output, but there are too many changes to test thoroughly. Adding formatting should be fairly safe though.
=> Add number formatting

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
Thanks to **sxtyzhangzk** for the code pointer! I just changed exactly what was described in this comment:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8104#issuecomment-889000350
I tested with the microwave grinder (since EBF and vacuum freezer are no longer in TecTech). When out of power, the machine controller cover switches its settings to "Disable machine".
* Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8104
=> Fix machine cover safe mode in TecTech

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Adds a recipe for the infinite oil rig from https://github.com/GTNewHorizons/GT5-Unofficial/pull/795
Shouldn't be merged until the previous PR is.
=> add recipe for infinite oil rig

src/main/java/com/github/technus/tectech/nei/TT_NEI_ResearchHandler.java, src/main/java/com/github/technus/tectech/nei/TT_NEI_ScannerHandler.java
This code was blindly copy-pasted and is the same as the one in GT5U before it was changed recently.  Since this override has the same behavior, the error was not previously noticed.
=> Don't override GT5U's GT_RectHandler

dependencies.gradle, src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
- Added TT MK4 fusion recipes.
- Bumped up stargate research cost (significant EU wise but if you're going for a stargate, should still be perfectly doable).
- UMV energy hatch/dynamo now correctly use UMV circuits (Pico) and not UXV (Quantum).
Planning on doing MK5 as well but that branch must be merged into GTPP first.
=> MK4 Recipes, stargate adjustment and UMV circuit fix.

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java, src/main/java/com/github/technus/tectech/recipe/TT_recipeAdder.java
just find out that assline can support different input recipes. so don't need to register a place holder recipe for xsmd and asmd recipes.
tested in game, everything runs fine.
=> Remove the place holder recipe of xSMD

src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_Param.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/gui/GT_Container_ParamAdv.java
Added casts to long to fix overflow when doing the bit-manpulation. Doing this allows the Parametrizer X to work as intended.
Fix for issue [#GTNewHorizons/GT-New-Horizons-Modpack@10791 ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10791)
=> Parametrizer X Bugfix

src/main/java/com/github/technus/tectech/mechanics/enderStorage/EnderLinkTag.java, src/main/java/com/github/technus/tectech/mechanics/enderStorage/EnderWorldSavedData.java, src/main/java/com/github/technus/tectech/thing/cover/GT_Cover_TM_EnderFluidLink.java
Change ender fluid link to use text instead of a color hex,
Breaks old setup but makes it easier to setup and remember channel names in the future
=> Change ender fluid link covers frequency to be text instead of a color hex

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
xsmds are already allowed for all other wetware circuits. This one was just an oversight.
related to https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/353, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10588
=> Allow xsmds for wetwaremainframe

src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_BuckConverter.java
Currently Buck converters have a passive loss of 1A of the tier below. So a UV one has a passive loss of 1A ZPM when running. I think they shouldn't have a loss considering they're more expensive and can only take in 2A
=> Remove the loss from buck converters

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_dataBank.java
This change allows databank to be daisy chained at the cost of more power. Just add a Assembly Line Slave connector to another databank to link data sticks between them. This removes the tedium of having to replicate all data sticks between multiple data banks later on
=> Allow databanks to be daisy chained

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Changed the recipe for the Draconic Evolution Fusion Crafter controller.
This multi is now the new method to obtain Draconic Cores and upgrade them. Further recipes are being added to it as well. As such it should not be tiered in LuV but in UHV, same as the old method.
I also added a primordial pearl and some BM Shards which were part of the old (soon to be removed) quest line directly to the controller recipe. Furthermore, I added a dense Gaia plate to improve botania integration into the pack.
However I have not added any HEE or any hard dependency on the T8 rocket (you still need UHV materials) which were both also part of the old method as those were generally disliked features. :)
The screenshot is with a texturepack but I hope thats clear anyway (thats a UHV assembler and UHV …
=> Changed DEFC controller recipe and moved it to TecTech

src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_Rack.java
biomainframe 40->44 (see ticket)
nano 48 -> 50 (to set it apart a bit)
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9916.
=> Minor biomainframe and nano circuit computation buff

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_research.java
Added texture offset to make the object holder take the adv computer casing texture
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11135
=> Object Holder Texture Fix

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_computer.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
Added a timeout to TT MB base so that machines dont stop after a world reload, as in some cases where the Research Station was loaded before the Quantum Computer, the Research could still fail. Now the Research Station waits a few ticks after the computation has cut off before it shuts off.
=> Computation Timeout

src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_InputDataItems.java
Return ghost item instead of actual item to prevent dropping when the Assembly Line Slave Connector is broken
=> Fix Assembly Line Slave Connector dropping all Data Sticks

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
MAX Circuits are very far away and UMV hatches in general are craftable, so why gate UMV wireless by unobtainable items?
=> Make UMV Wireless Energy/Dynamo hatches craftable

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java
Added start and end processing calls like in the regulat MB base class, which will properly update the stocking input bus.
This is regarding https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/62
We'll need to update the tt dep of gg after merge
=> Fix ME Stocking input bus dupe fix for all TT based MBs

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_TM_teslaCoil.java
from LV to ZPM should be 7 tiers
=> fix Tesla Tower can't recognize LuV coil

dependencies.gradle, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_InputDataItems.java
Could possibly be the cause of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11619
=> Use new API call instead of hack to prevent dropping of data sticks

src/main/java/com/github/technus/tectech/TecTech.java, src/main/java/com/github/technus/tectech/mechanics/enderStorage/EnderWorldSavedData.java
Currently when you create world A, set up the fluid cover and fill it with fluid. Then enter world B, set up the same frequency, you would be able to transfer the fluid from save A to B. This is now fixed by invalidating the Fluid Cover map on world unload.
=> Fix persistant ender link data bug

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java, src/main/java/com/github/technus/tectech/loader/thing/MachineLoader.java, src/main/java/com/github/technus/tectech/thing/CustomItemList.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_PipeBlock_Data.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_PipeBlock_EM.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_PipeBlock_Energy.java
Added a full block pipe variant to fix visual issues like:
by adding:
=> Added full block variant of all pipe types

dependencies.gradle, src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Adds a recipe for the extremely Ultimate battery and a one-step alternate recipe for the energy module. Said alternate recipe is (realistically) dtpf locked so that the really ultimate battery still has to be crafted without it at least once. 
Extremely Ultimate Battery:
Energy Module:
=> Extremely Ultimate recipe + 1-step energy module

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
They were broken by the EC2 removal glod did.
=> EoH recipe fixes

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Replaces the bio board used in pico circuits to an optical board, as that is the highest tier board now
=> Swap pico circuit board

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
Removes recipes for optical memory because they have been moved to the space assembler in coremod
Needs https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/530
=> Remove Optical memory recipes

src/main/resources/assets/tectech/lang/en_US.lang
=> Remove Mistake in description of Energy Infuser

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
The UXV sensor requires 16 plates, while all other LuV+ sensors require 8
This PR reduces the plate amount to 8 to match the other sensors
=> Fix plate amount in UXV sensor recipe

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
fixes: 
reinforced spatial/temporal casings not having the correct space elevator blocks
gallifreyan spacetime compression recipe time being too long
temporal casings requiring spatially enlarged fluid instead of tachyon rich fluid
=> Misc recipe fixes for EOH blocks

src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java
The number of digital singularities used in the first 4 tiers was 1, 3, 4, 4
changed it to 1, 2, 3, 4
=> Fix digital singularity amounts in spacetime compression field gens

dependencies.gradle, src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
This PR adds recipes for the mk5 fusion controller, casing and coil.
Also fixes the fusion mk4 controller recipe using sc base uhv instead of sc uhv.
Controller:
Coil:
Casing:
=> Fusion mk5 recipes + mk4 recipe fix

src/main/java/com/github/technus/tectech/loader/recipe/Assembler.java
Adds recipes for all UXV multi amp dynamos and energy hatches as well as all UXV laser source and target hatches 
The recipes follow the previous tiers, just with UXV parts/materials
1M amp UXV laser source as an example:
=> Add UXV laser & multi-amp recipes

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Fixes the estimated eu/t formula.
Previously it was a simple eu output divided by recipe time which was not accurate at all, as there's a few factors that have to be taken into account.
Also fixes the eu output as it depends on stabilisation tier now
=> Fix EOH estimated eu/t formula

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/github/technus/tectech/loader/recipe/Assembler.java
Fixes an oversight in the recipes for the new multiamp EV hatches from https://github.com/GTNewHorizons/TecTech/pull/139. They were missing the transformers.
=> Adjust ev multiamp hatch recipes

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_transformer.java
* will be turned off after build
* the on/off button in the gui is enabled
Auto-activating a multiblock that can explode while the structure is breaking down is not a good idea
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13434
=> EM_transformer

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Redo of the EOH overclock formula to make overclocks more reasonable power cost wise. 
The old formula increases the power cost by a ludicrous amount, making overclocks completely unusable at higher EOH tiers. 
This new formula aims to fix that issue and make overclocks viable.
Comparison of the two formulas can be found here
https://www.desmos.com/calculator/46gizo08do
=> Rework EOH overclock formula

src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_DebugPowerGenerator.java
This small patch allows you to type in the voltage and amperage you want. The old buttons are still there and functional for anyone who is committed to using them. 
The new UI looks like this:
=> Debug Generator GUI Improvements

src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
Pico: replaced some low tier materials with more tier appropriate ones
Niobium titanium foil -> radox foil
Osmium bolts -> trans metal bolts
Quantum: lowered processing voltage to umv to allow it being crafted in the AAL pre-universium
=> Pico & Quantum circuit adjustments

src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
Removes the 1-step assline lapo battery recipes in favor of https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/642
=> Remove 1-step assline lapo battery recipes

src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
This recipe was "buffed" by ~170x by someone to a nonsense number. The user at this tier is making likely in the region of 500B EU/t, if not more. OCing this 5-6 times will cost 236B - 1T EU/t and take 375-750 seconds. A much more reasonable value.
For comparison, this multi at its best makes 12T EU/t, that means that the EU cost to craft this currently is 6% of 1 tick of energy output. This is clearly absurd.
In future please discuss content changes with the actual author to get intent rather than randomly changing things.
=> Fix EOH recipe time

build.gradle, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_infuser.java, src/main/resources/assets/tectech/lang/en_US.lang
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13749
Simply using `getStackInSlot` instead of direct access to `mInventory` fixes the issue, but we still don't have way to change NBT of items in the ME network. Since it's very niche usage, I just excluded support for stocking bus.
=> Fix energy infuser and stocking bus interaction

src/main/java/com/github/technus/tectech/thing/item/ParametrizerMemoryCard.java
Before it checked both values of a hatch to be non-null. But it's fine if one is null. The other can still be copied.
=> Fix memory card not copying all parameters

src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_WirelessMulti.java
The old way seems to be voiding energy every time the hatch loads; this attempts to fix it.
=> Fix wireless energy voiding

src/main/java/com/github/technus/tectech/loader/gui/CreativeTabTecTech.java
fix creative tab NPE caused by #246
=> Fix creative tab NPE

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
Before this change the EOH would only check the first slot of the input bus for a circuit to get its overclocks from. Other than programmable circuits any other ItemStack that has damage would also work to get the overclocks from. This pr makes it so all slots get checked for a circuit including the ghost circuit slot.
=> EOH now checks for all possible circuits in input bus

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
this pr blacklists the stocking input bus from the EOH to prevent exploitation of astral array amounts & reduces the chance penalty of time dilation field generators from 10 to 9.25% per tier to both make EOH progression a tad easier and increase universium production to make it a bit more fair compared to the previous state.
=> Some more EOH changes

src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java, src/main/java/com/github/technus/tectech/loader/thing/MachineLoader.java, src/main/java/com/github/technus/tectech/thing/CustomItemList.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_CreativeUncertainty.java, src/main/resources/assets/tectech/lang/en_US.lang
Don't need to waste time playing little game when testing quantum computer in creative mode.
=> Add debug uncertainty

gradle.properties, settings.gradle, src/main/java/com/github/technus/tectech/thing/cover/GT_Cover_TM_TeslaCoil.java
Changed check to 10 ticks from 10 seconds to fix power failing on server starting.
Fixes [#14000](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14000)
=> Fixing power checks from telsa tower

dependencies.gradle, settings.gradle, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_Uncertainty.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_BuckConverter.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_DebugPollutor.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_DebugPowerGenerator.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_DebugStructureWriter.java, src/main/java/com/github/technus/tectech/util/TT_Utility.java
* Replaces text fields where the user is expected to input a number with NumericWidget, supporting extended syntax and formatting. (See https://github.com/GTNewHorizons/ModularUI/pull/62.)
* Replaces instances where a dynamic text field is being communicated between server and client with a purely client-side method. In some cases this allows the client to do localization on these texts correctly. (See https://github.com/GTNewHorizons/ModularUI/pull/69.)
* Modifies other instances where the UI displays a number to use a locale-aware formatter. (See https://github.com/GTNewHorizons/ModularUI/pull/67.)
&nbsp;
Notes:
* I have not touched Parametrizer Hatches, they are deprecated and uncraftable, even though they contain some code that should have been changed if they were still intended to …
=> Numeric widget and localized number formatting.

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java, src/main/java/com/github/technus/tectech/util/TT_Utility.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15706
Destroy renderer when machine is shut down or controller is destroyed.
Prevent possible long overflow of output and input EU.
Save 2 variables to NBT for scanner info.
Description:
- No more camelCase
- More legible parallel formulas 
- I don't see any direct solution to fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15291, so the stuff-voiding description is deleted, as another solution :trollface:  
- Add power output penalty description under stabilisation section, rather than hiding it somewhere
Scanner info:
- Display the fancy prefix of 3 tiered blocks
- Display EU output, input and EUt in standard form (also fix long overflow)
- Add star matter & stellar plasma output rate
=> EOH fix no power output & description and scanner info changes

src/main/java/com/github/technus/tectech/thing/cover/GT_Cover_TM_TeslaCoil.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_TM_teslaCoil.java, src/main/java/com/github/technus/tectech/thing/metaTileEntity/single/GT_MetaTileEntity_TeslaCoil.java
As this issue [*](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14727) said, the tesla leaks memory and will finally increase mspt and crash the server.
Tesla controller block didn't implement onUnload() method, so when chunk unloads, it will leak a controller TE object.
Tesla cover didn't implement onCoverRemoval() method, so when it's removed from hatches, a TeslaCoverConnection object leaks.
And I suggest removal of tesla cover, or do completely rework on tesla, because there's no callback for covers when the chunk unloads or the hatch it attaches get removed. So there's no chance for developer to remove the TeslaCoverConnection object from set to release the memory.
You shouldn't do any side effects in cover logic, unless you make sure you can handle it.
=> Fix memory leak by tesla, but problem still exists when using tesla cover.

dependencies.gradle, src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_EnergyMulti.java, src/main/resources/assets/tectech/lang/en_US.lang
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15842.
&nbsp;
Note: Can somebody please test this? In my dev environment the new tooltip does not show until I delete and regenerate `GregTech.lang`. I'm not sure if this is something to do with me, or if TT is not updating this file correctly.
Edit: should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2552.
=> Show amperes in/out in tooltip of energy hatches.

src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
This pr addresses some recipe conflicts that can happen between different EOH dilation casings.
- T1-T2 all use white dwarf matter and mk2 fusions
- T4-T5 all use black dwarf matter and mk3 fusions
- T8-T9 all use MHDCSM and mk4 fusions
=> Fix conflicting recipes for EOH dilation parts.

src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_TM_teslaCoil.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16268
=> Generate node map on checkMachine
